[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate --schema=prisma/schema.prisma", "npm run build"]
dependsOn = ["install"]

[start]
cmd = "npx prisma migrate deploy && npm start"
